// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const SignInLazyImport = createFileRoute('/sign-in')()
const ReportLazyImport = createFileRoute('/report')()
const PostsLazyImport = createFileRoute('/posts')()
const IndexLazyImport = createFileRoute('/')()
const PostPostIdLazyImport = createFileRoute('/post/$postId')()

// Create/Update Routes

const SignInLazyRoute = SignInLazyImport.update({
  path: '/sign-in',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/sign-in.lazy').then((d) => d.Route))

const ReportLazyRoute = ReportLazyImport.update({
  path: '/report',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/report.lazy').then((d) => d.Route))

const PostsLazyRoute = PostsLazyImport.update({
  path: '/posts',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/posts.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const PostPostIdLazyRoute = PostPostIdLazyImport.update({
  path: '/post/$postId',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/post.$postId.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/posts': {
      preLoaderRoute: typeof PostsLazyImport
      parentRoute: typeof rootRoute
    }
    '/report': {
      preLoaderRoute: typeof ReportLazyImport
      parentRoute: typeof rootRoute
    }
    '/sign-in': {
      preLoaderRoute: typeof SignInLazyImport
      parentRoute: typeof rootRoute
    }
    '/post/$postId': {
      preLoaderRoute: typeof PostPostIdLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  PostsLazyRoute,
  ReportLazyRoute,
  SignInLazyRoute,
  PostPostIdLazyRoute,
])
